### ISSUE TITLE
SakuraBotでfreeRTのissueを消化する。

### ISSUE THREAD

**Issue by yaakiyu** [SakuraProject/sakura-general#2]
freeRTのissueたちをSakurabotの方に実装してcloseする計画。
全部で39個のissueがある。
* [x] SakuraProject/rt-bot#2
* [ ] SakuraProject/rt-bot#6
* [ ] SakuraProject/rt-bot#11
* [ ] SakuraProject/rt-bot#12
* [ ] SakuraProject/rt-bot#16
* [ ] SakuraProject/rt-bot#17
* [ ] SakuraProject/rt-bot#18
* [ ] SakuraProject/rt-bot#19
* [ ] SakuraProject/rt-bot#31
* [ ] SakuraProject/rt-bot#74
* [ ] SakuraProject/rt-bot#81
* [ ] SakuraProject/rt-bot#98
* [ ] SakuraProject/rt-bot#103
* [ ] SakuraProject/rt-bot#104
* [ ] SakuraProject/rt-bot#105
* [ ] SakuraProject/rt-bot#106
* [ ] SakuraProject/rt-bot#107
* [ ] SakuraProject/rt-bot#108
* [ ] SakuraProject/rt-bot#109
* [ ] SakuraProject/rt-bot#110
* [ ] SakuraProject/rt-bot#111
* [ ] SakuraProject/rt-bot#112
* [ ] SakuraProject/rt-bot#113
* [ ] SakuraProject/rt-bot#114
* [ ] SakuraProject/rt-bot#115
* [ ] SakuraProject/rt-bot#116
* [ ] SakuraProject/rt-bot#117
* [ ] SakuraProject/rt-bot#118
* [ ] SakuraProject/rt-bot#119
* [ ] SakuraProject/rt-bot#121
* [ ] SakuraProject/rt-bot#122
* [ ] SakuraProject/rt-bot#123
* [ ] SakuraProject/rt-bot#124
* [ ] SakuraProject/rt-bot#125
* [ ] SakuraProject/rt-bot#126
* [ ] SakuraProject/rt-bot#127
* [ ] SakuraProject/rt-bot#128
* [ ] SakuraProject/rt-bot#129
* [ ] SakuraProject/rt-bot#134

**Comment by ysmreg** [comment]
mp3とmp4の再生はSakurabotに実装済みです
